---
- name: Create dotnetdev.list file
  command: touch /etc/apt/sources.list.d/dotnetdev.list creates="/etc/apt/sources.list.d/dotnetdev.list"

- name: Set apt-get feed for Ubuntu Xenial
  lineinfile: dest=/etc/apt/sources.list.d/dotnetdev.list line="deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16" 

- name: Set apt-get feed for Ubuntu Trusty
  lineinfile: dest=/etc/apt/sources.list.d/dotnetdev.list line="deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- name: Add apt key
  apt_key: keyserver=apt-mo.trafficmanager.net id=417A0893

- name: Install dotnet core SDK
  apt: name=dotnet-dev-1.0.0-preview2-003131 state=present update_cache=yes
